export const config = {
  password: process.env.DASHBOARD_PASSWORD ?? "changeme",
  secret: process.env.DASHBOARD_SECRET ?? "default-secret-change-me-in-prod",
  evoApiUrl: process.env.EVO_API_URL ?? "http://10.0.2.4:8080",
  evoApiKey: process.env.EVO_API_KEY ?? "",
  evoInstance: process.env.EVO_INSTANCE ?? "org_00000000",
  alertPhone: process.env.ALERT_PHONE ?? "",
  cookieName: "ops-session",
  sessionDuration: 7 * 24 * 60 * 60,
  domains: [
    "pagamentos.glifodev.com",
    "anacardier.glifodev.com",
    "previaotorrino.glifodev.com",
    "eleitoapp.com",
    "eleitoapp.com.br",
    "matrix.glifodev.com",
    "evo.glifodev.com",
    "painel.glifodev.com",
    "mindcare.glifodev.com",
    "api.mindcare.glifodev.com",
    "coolify.glifodev.com",
    "gmrural.com.br",
    "oglifo.com",
    "oglifo.com.br",
  ],
  alertDefaults: {
    diskWarningPercent: 85,
    ramMinAvailableMb: 500,
    swapMaxPercent: 80,
    loadMaxMultiplier: 2,
    sslExpiryWarningDays: 14,
    backupMaxAgeHours: 25,
    cooldownMinutes: 30,
  },
} as const;
